dist: xenial
language: c

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-9-2019-q4-major
    - $HOME/nrf_sdk/16.0.0

env:
  global:
    - GNU_INSTALL_ROOT="$HOME/gcc-arm-none-eabi-9-2019-q4-major/bin/"
    - NORDIC_SDK_PATH="$HOME/nrf_sdk/16.0.0"
    - PATH="$PATH:$HOME/gcc-arm-none-eabi-9-2019-q4-major/bin"

  matrix:
    - BOARD=sparkfun-pro-mini # Release
    - BOARD=sparkfun-pro-mini DEBUG=1 # Debug

    - BOARD=mdk-usb-dongle # Release
    - BOARD=mdk-usb-dongle DEBUG=1 # Debug

    - BOARD=mdk # Release
    - BOARD=mdk DEBUG=1 # Debug

    - BOARD=pca10059 # Release
    - BOARD=pca10059 DEBUG=1 # Debug

    - BOARD=pbrick # Release
    - BOARD=pbrick DEBUG=1 # Debug


before_install:
  - chmod +x $TRAVIS_BUILD_DIR/.travis/before_install.sh

install:
  - $TRAVIS_BUILD_DIR/.travis/before_install.sh
  # Verify the arm-none-eabi-gcc binary is working correctly
  - arm-none-eabi-gcc --version
  - if env | grep -q ^PBRICK_LIGHT_CUSTOM=; then cp $TRAVIS_BUILD_DIR/.travis/pbrick_light_custom.c $TRAVIS_BUILD_DIR; fi
  - if env | grep -q ^PBRICK_CUSTOM=; then cp $TRAVIS_BUILD_DIR/.travis/pbrick_custom.h $TRAVIS_BUILD_DIR; fi

script:
  - make
